version: '0.1'
services:
  frontend:
    image: frontend
    ports:
      - 80:80
    restart: always
      
  backend:
    image: backend
    restart: always

  database:
    image: database
    restart: always
    environment:
      # Create a .env file to store these values in. NEVER upload .env file to repository.
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: